fix: add verification if the current folder is inside a repository, and update README.md

diff --git a/gendo b/gendo
--- a/gendo
+++ b/gendo
@@ -1,3 +1,8 @@
 #!/bin/bash
 
-python3 ~/gendo/main.py $@
+if [ -d ".git" ]; then
+    python3 ~/gendo/main.py $@
+else
+    echo "Error: This is not a git repository"
+    exit 1
+fi
